"""
Daily SQLite snapshot + retention.

Why
---
The DB is the only thing that can't be regenerated by re-running scrapers
— it carries the operator's CRM stages, notes, score history, image
hashes, and the geocode cache. Losing it costs days. This module makes a
zipped snapshot every day and keeps the last N runs, so a corruption
event or accidental delete is a one-line restore away.

Behaviour
---------
- ``backup_now()`` calls SQLite's online ``VACUUM INTO`` to produce a
  clean snapshot WHILE the live DB keeps serving (no lock, no corruption
  window). The snapshot is then zipped and saved to
  ``data/backups/imovela-YYYYMMDD-HHMM.db.zip``.
- ``prune_old_backups(keep=14)`` deletes snapshots older than the latest
  ``keep`` files so the folder doesn't grow forever.
- Postgres is detected and logs a clear message — for managed Postgres
  the backup is the provider's responsibility; this module is a no-op.

Integration
-----------
- CLI: ``python main.py backup`` (one-shot)
- Scheduler: daily IntervalTrigger added to ``scheduler/jobs.py`` so
  ``python main.py scheduler`` produces a snapshot every 24h.
"""
from __future__ import annotations

import os
import shutil
import zipfile
from datetime import datetime
from pathlib import Path
from typing import Optional

from utils.logger import get_logger

log = get_logger(__name__)


def _backup_dir() -> Path:
    from config.settings import settings
    p = settings.data_dir / "backups"
    p.mkdir(parents=True, exist_ok=True)
    return p


def _sqlite_path() -> Optional[Path]:
    """Return the active SQLite DB path, or None when on a non-SQLite backend."""
    from config.settings import settings
    if not settings.is_sqlite:
        return None
    # database_url like sqlite:///absolute/path.db
    raw = settings.database_url.replace("sqlite:///", "", 1)
    p = Path(raw).resolve()
    return p if p.exists() else None


# ── Public API ───────────────────────────────────────────────────────────────

def backup_now(label: Optional[str] = None) -> dict:
    """
    Take an online snapshot of the SQLite DB, zip it, and persist to disk.

    ``label`` is appended to the filename (e.g. "post-overnight") so manual
    snapshots are easy to spot. Returns a stats dict with the path size.
    """
    db_path = _sqlite_path()
    if not db_path:
        log.info("[backup] non-SQLite backend — managed by your DB provider")
        return {"skipped": True, "reason": "non-sqlite"}

    timestamp = datetime.utcnow().strftime("%Y%m%d-%H%M")
    suffix = f"-{label}" if label else ""
    snap_name = f"imovela-{timestamp}{suffix}.db"
    snap_path = _backup_dir() / snap_name
    zip_path  = snap_path.with_suffix(".db.zip")

    # 1. Online snapshot (VACUUM INTO) — single sqlite3 connection.
    import sqlite3
    try:
        with sqlite3.connect(str(db_path)) as src:
            src.execute(f"VACUUM INTO '{snap_path.as_posix()}'")
    except Exception as e:
        log.error("[backup] VACUUM INTO failed: {e}", e=e)
        return {"skipped": True, "error": str(e)}

    # 2. Zip + delete the unzipped copy
    try:
        with zipfile.ZipFile(
            zip_path, "w",
            compression=zipfile.ZIP_DEFLATED, compresslevel=6,
        ) as zf:
            zf.write(snap_path, arcname=snap_name)
        snap_path.unlink(missing_ok=True)
    except Exception as e:
        log.error("[backup] zip failed: {e}", e=e)
        snap_path.unlink(missing_ok=True)
        return {"skipped": True, "error": str(e)}

    size_mb = zip_path.stat().st_size / (1024 * 1024)
    log.info(
        "[backup] snapshot saved → {p} ({s:.1f} MB)",
        p=zip_path.name, s=size_mb,
    )
    return {
        "path":     str(zip_path),
        "size_mb":  round(size_mb, 2),
        "ts":       timestamp,
    }


def prune_old_backups(keep: int = 14) -> dict:
    """
    Keep only the latest ``keep`` snapshots; delete the rest.
    Returns stats about how many were removed and freed bytes.
    """
    backups = sorted(
        _backup_dir().glob("imovela-*.db.zip"),
        key=lambda p: p.stat().st_mtime,
        reverse=True,
    )
    keep_set = set(backups[:keep])
    removed = 0
    freed   = 0
    for f in backups[keep:]:
        try:
            freed   += f.stat().st_size
            f.unlink()
            removed += 1
        except Exception as e:
            log.debug("[backup] could not remove {f}: {e}", f=f.name, e=e)
    if removed:
        log.info(
            "[backup] pruned {n} old backups ({s:.1f} MB freed)",
            n=removed, s=freed / (1024 * 1024),
        )
    return {"removed": removed, "freed_mb": round(freed / (1024 * 1024), 2),
            "kept": len(backups) - removed}


def list_backups() -> list[dict]:
    """Return latest backups as ``[{name, size_mb, mtime}, ...]``."""
    out: list[dict] = []
    for f in sorted(
        _backup_dir().glob("imovela-*.db.zip"),
        key=lambda p: p.stat().st_mtime,
        reverse=True,
    ):
        st = f.stat()
        out.append({
            "name":     f.name,
            "path":     str(f),
            "size_mb":  round(st.st_size / (1024 * 1024), 2),
            "mtime":    datetime.fromtimestamp(st.st_mtime),
        })
    return out


# ── Restore helper ───────────────────────────────────────────────────────────

def restore_backup(zip_path: str, target_db_path: Optional[str] = None) -> dict:
    """
    Restore a zipped snapshot, OVERWRITING the active DB.

    Caller is responsible for stopping any running scraping/scheduler
    processes first; SQLite enforces a single writer at a time.
    """
    from config.settings import settings

    src = Path(zip_path)
    if not src.exists():
        return {"ok": False, "error": "snapshot not found"}

    target = Path(target_db_path) if target_db_path else _sqlite_path()
    if not target:
        return {"ok": False, "error": "no SQLite target"}

    # Make a safety backup of the current DB first
    safety = target.with_suffix(target.suffix + ".pre-restore.bak")
    if target.exists():
        shutil.copy2(target, safety)

    try:
        with zipfile.ZipFile(src) as zf:
            members = zf.namelist()
            if not members:
                return {"ok": False, "error": "empty zip"}
            zf.extractall(target.parent)
            extracted = target.parent / members[0]
            shutil.move(str(extracted), str(target))
    except Exception as e:
        log.error("[backup] restore failed: {e}", e=e)
        if safety.exists():
            shutil.copy2(safety, target)
        return {"ok": False, "error": str(e)}

    log.info("[backup] restored {z} → {t} (safety: {s})",
             z=src.name, t=target, s=safety.name)
    return {"ok": True, "restored_from": str(src), "safety_copy": str(safety)}
